{% set version = "1.3.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genv/genv-{{ version }}.tar.gz
  sha256: 4af5d6c1e6b512d5d01525a5fe4f420db72902d6db74e99df08174d5f84994b1

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - genv --help

about:
  home: https://github.com/run-ai/genv
  summary: GPU environment and cluster management
  description: |
    Genv lets you easily control, configure, monitor and enforce the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
