{% set version = "1.1.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genv/genv-{{ version }}.tar.gz
  sha256: 9ab408ca1ecac58bb8d8eaee57ea9331bc231d034911715bce96b5526cd371e6

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - genv --help

about:
  home: https://github.com/run-ai/genv
  summary: GPU environment and cluster management
  description: |
    Genv lets you easily control, configure, monitor and enforce the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
