{% set version = "0.6.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://github.com/run-ai/genv/archive/v{{ version }}.tar.gz
  sha256: d7d1eac91c399f517ccf8674751a01a66c088d0d2c70a0d76832579dfc9b5908

build:
  skip: true  # [win]
  number: 0

requirements:
  run:
    - python

test:
  commands:
    - genv help

about:
  home: https://github.com/run-ai/genv
  summary: GPU Environment Management
  description: |
    genv lets you easily control, configure and monitor the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
