{% set version = "0.10.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://github.com/run-ai/genv/archive/v{{ version }}.tar.gz
  sha256: 57a73900b9a608b23189afc6bfb1e7a5b2eb3e5832f319c5207929d1e9e6db0f

build:
  skip: true  # [win]
  number: 0

requirements:
  run:
    - python

test:
  commands:
    - genv help

about:
  home: https://github.com/run-ai/genv
  summary: GPU Environment Management
  description: |
    genv lets you easily control, configure and monitor the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
