{% set version = "1.4.2" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genv/genv-{{ version }}.tar.gz
  sha256: b618b7617191a958d59b5f7045d98ff89ac95ae8f30340b04e50bdb036bad5ee

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - psutil
    - setuptools

test:
  commands:
    - genv version

about:
  home: https://github.com/run-ai/genv
  summary: GPU environment and cluster management
  description: |
    Genv lets you easily control, configure, monitor and enforce the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
