{% set version = "0.7.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://github.com/run-ai/genv/archive/v{{ version }}.tar.gz
  sha256: a291bea2caf5f807096b79adc44463c5e524d5c65db8e445b8b19c07b6b664f6

build:
  skip: true  # [win]
  number: 0

requirements:
  run:
    - python

test:
  commands:
    - genv help

about:
  home: https://github.com/run-ai/genv
  summary: GPU Environment Management
  description: |
    genv lets you easily control, configure and monitor the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
