{% set version = "1.0.0" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genv/genv-{{ version }}.tar.gz
  sha256: 16f1be93c91e2b0216128e192eeb7e5a8001b4d53367c10fd0c0bac86aa11aaa

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - genv --help

about:
  home: https://github.com/run-ai/genv
  summary: GPU environment and cluster management
  description: |
    Genv lets you easily control, configure, monitor and enforce the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
